### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Utilities/ms-data-core-api#15]
@Tobias-Ternent Can we check the travis integration of ms-data-core-api. Is failing

**Comment by Tobias-Ternent** [comment]
Fixed by:

1. Removed builds for Java 8 and 6, because in the POM it's defined only for 7.
2. Whitelisted builds only Master.
3. Truncated the hostname, which is causing a buffer overflow error with openJDK builds in Travis since December.https://github.com/PRIDE-Utilities/ms-data-core-api/commit/7d1e0d494cc07195454a5e12eba9630c8b735227
