### ISSUE TITLE
The EBI repo is down?

### ISSUE THREAD

**Issue by fcyu** [PRIDE-Utilities/ms-data-core-api#23]
I cannot download the library from maven.

**Comment by Tobias-Ternent** [comment]
I'm sorry, our EMBL-EBI infrastructure is down since Friday for essential maintenance. Systems have started to come back up since yesterday, but not everything has just yet, so it's taking more time to get back to normal. 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Important: Our campus data centre will be undergoing essential maintenance this weekend - <a href="https://t.co/BGJBOtzBcL">https://t.co/BGJBOtzBcL</a> <a href="https://t.co/Wc1BnNLDnI">pic.twitter.com/Wc1BnNLDnI</a></p>&mdash; EMBL-EBI (@emblebi) <a href="https://twitter.com/emblebi/status/769107090912731136">August 26, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by fcyu** [comment]
Dear @Tobias-Ternent 

Thanks for your reply. I have a suggestion. Please refer to [https://github.com/PRIDE-Utilities/jmzml/issues/18#issuecomment-245147936](url)

Thanks.

**Comment by Tobias-Ternent** [comment]
Yes, thanks for that. We're going to review this in our team, and see how feasible it is to release to a more central repository in the near future in order to avoid these downtime problems. Personally, I think it's the best option because it would also remove the need to administer our own Nexus.

**Comment by ypriverol** [comment]
Dear @fcyu 
 The nexus server is now back. Our development team has been discussing other strategies to deploy 
 and we have a road-map for the future. Again, thanks for your patience. 
Regards 
Yasset
